version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - db_data:/app
    environment:
      - DEBUG=1
    command: sh -c "python src/manage.py makemigrations && python src/manage.py migrate && python src/manage.py collectstatic --noinput && python src/manage.py get_google_reviews && python src/manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped

volumes:
  db_data: 