# Generated by Django 5.0.7 on 2025-07-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('href', models.URLField(max_length=512)),
                ('avatar_url', models.URLField(max_length=512)),
                ('text', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.CharField(blank=True, max_length=512, null=True)),
                ('profile_url', models.URLField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=256)),
                ('last_executed', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
