# Generated by Django 5.0.7 on 2025-07-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReviewStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_reviews', models.PositiveBigIntegerField(default=0)),
                ('total_rating', models.PositiveBigIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
            ],
        ),
    ]
